Moved visualization initialization
The visualization was causing the following:
ERROR: LoadError: UndefVarError: Visualizer not defined

I moved it to after the dependencies are loaded